"""create_metrics_table

Revision ID: 35934f60a720
Revises: 9b7904214874
Create Date: 2026-04-28 16:28:18.642510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35934f60a720'
down_revision: Union[str, None] = '9b7904214874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_collected_at'), 'metrics', ['collected_at'], unique=False)
    op.create_index(op.f('ix_metrics_instance_id'), 'metrics', ['instance_id'], unique=False)
    op.create_index('ix_metrics_instance_name_collected', 'metrics', ['instance_id', 'metric_name', 'collected_at'], unique=False)
    op.create_index(op.f('ix_metrics_metric_name'), 'metrics', ['metric_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_metric_name'), table_name='metrics')
    op.drop_index('ix_metrics_instance_name_collected', table_name='metrics')
    op.drop_index(op.f('ix_metrics_instance_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_collected_at'), table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###