"""create_maintenance_tables

Revision ID: 5775b79fc8d4
Revises: f78e726997b6
Create Date: 2026-04-30 15:54:54.995350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5775b79fc8d4'
down_revision: Union[str, None] = 'f78e726997b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('VACUUM', 'VACUUM_FULL', 'ANALYZE', 'REINDEX', 'KILL_IDLE', 'KILL_LONG', name='tasktype'), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['database_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_schedules_instance_id'), 'maintenance_schedules', ['instance_id'], unique=False)
    op.create_index(op.f('ix_maintenance_schedules_next_run_at'), 'maintenance_schedules', ['next_run_at'], unique=False)
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('VACUUM', 'VACUUM_FULL', 'ANALYZE', 'REINDEX', 'KILL_IDLE', 'KILL_LONG', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('target_table', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['database_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_tasks_instance_id'), 'maintenance_tasks', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_tasks_instance_id'), table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_schedules_next_run_at'), table_name='maintenance_schedules')
    op.drop_index(op.f('ix_maintenance_schedules_instance_id'), table_name='maintenance_schedules')
    op.drop_table('maintenance_schedules')
    # ### end Alembic commands ###