"""create_database_instances_table

Revision ID: a1487ff4454d
Revises: 04fd90b1a981
Create Date: 2026-04-10 17:44:05.907163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1487ff4454d'
down_revision: Union[str, None] = '04fd90b1a981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROVISIONING', 'RUNNING', 'STOPPED', 'DELETING', 'DELETED', 'FAILED', name='instancestatus'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('db_name', sa.String(length=255), nullable=True),
    sa.Column('db_user', sa.String(length=255), nullable=True),
    sa.Column('connection_uri', sa.Text(), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True, comment='Number of vCPUs allocated'),
    sa.Column('memory_mb', sa.Integer(), nullable=True, comment='RAM in megabytes'),
    sa.Column('storage_gb', sa.Integer(), nullable=True, comment='Disk storage in gigabytes'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_instances_name'), 'database_instances', ['name'], unique=False)
    op.create_index(op.f('ix_database_instances_status'), 'database_instances', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_database_instances_status'), table_name='database_instances')
    op.drop_index(op.f('ix_database_instances_name'), table_name='database_instances')
    op.drop_table('database_instances')
    # ### end Alembic commands ###