"""create_backups_and_backup_schedules_tables

Revision ID: f78e726997b6
Revises: 35934f60a720
Create Date: 2026-04-29 15:22:41.094257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78e726997b6'
down_revision: Union[str, None] = '35934f60a720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('strategy', sa.Enum('LOGICAL', 'PHYSICAL', name='backupstrategy'), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False, comment="Standard 5-field cron expression, e.g. '0 2 * * *'"),
    sa.Column('retention_days', sa.Integer(), nullable=False, comment='How many days to keep backups created by this schedule'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_schedules_instance_id'), 'backup_schedules', ['instance_id'], unique=False)
    op.create_index(op.f('ix_backup_schedules_next_run_at'), 'backup_schedules', ['next_run_at'], unique=False)
    op.create_table('backups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('backup_type', sa.Enum('MANUAL', 'SCHEDULED', name='backuptype'), nullable=False),
    sa.Column('strategy', sa.Enum('LOGICAL', 'PHYSICAL', name='backupstrategy'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'DELETED', name='backupstatus'), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True, comment='Absolute path to the backup file or directory on the host'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When this backup should be deleted by the retention job'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_instance_id'), 'backups', ['instance_id'], unique=False)
    op.create_index('ix_backups_instance_strategy_created', 'backups', ['instance_id', 'strategy', 'created_at'], unique=False)
    op.create_index(op.f('ix_backups_status'), 'backups', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backups_status'), table_name='backups')
    op.drop_index('ix_backups_instance_strategy_created', table_name='backups')
    op.drop_index(op.f('ix_backups_instance_id'), table_name='backups')
    op.drop_table('backups')
    op.drop_index(op.f('ix_backup_schedules_next_run_at'), table_name='backup_schedules')
    op.drop_index(op.f('ix_backup_schedules_instance_id'), table_name='backup_schedules')
    op.drop_table('backup_schedules')
    # ### end Alembic commands ###